site_name: kunfoo.org
site_url: https://kunfoo.org/
copyright: Die Katze
theme:
  name: simple-blog
  theme_style: light
  logo: assets/katze.png
  components:
    site_name: true
    title: false
    preview: true
    menu: true
    footer: false
nav:
  - Home: index.md
  - Internetperlen: perlen.md
  - Logbook: logbook.md
  - Kultur: kultur.md
  - Komputer: komputer.md
  - Fahrrad: fahrrad.md
